[package]
name = "fadroma-bench"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fadroma = { version = "0.8.8", features = ["scrt"] }
serde = { version = "1.0" }